# Site settings
title: Blog
email: weston.anderson@gmail.com
description: "Thoughts on life, liberty, and the pursit of happiness.  Seeking knowledge, gaining insight, and a modest appetite for adventure"
baseurl: "/blog"
url: "http://wseibold.github.io"
twitter_username: W_Seibold
github_username:  WSeibold
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
